script: gradle build
language: android
android:
  components:
  - build-tools-26.0.2
  - android-26
  - tools
  - platform-tools
  - tools
  licenses:
  - android-sdk-license-.+
deploy:
  provider: releases
  api_key:
    secure: eMpefvk1WASJ/4O1CnvLoCMW0i1jK6wL8tU9VuMGg2jveGh5DqeUibaK8vI5FkAptcYfoP0EQqsUCseNZ0a0l2wbQP2ZjB3nCkEWox8SKAW9UiH5ozSMVWeHa4BorhMiBDGavzXYSCQ2RIBO3KcvnngH9NrMjvmtZgY1TMlMSD1PIf9jEeFpZCYYw96b0tP2ZnQkAEK5XqsGrJReeuIliGe+/leu7e4U8+Cb8T0sTLlNYdbaF25r7w2xlHOqMtCqUQwpjWbGju2iFy51zM153uy9ZhSrbsq0UuSEe4Ies4X7qqRhM7rduKMRaha8UMaHhRliYmu8lyKLmm6dN/g8Fds7tbOc1St2YsB7+0ZxhiEg1lpob2Bp3LCvVlfGNx7fSbLqkhd46kiGVtuCkA7sFv0kPvFpnf0pAsYUpl3pL21mF1t88sFS9GUsmmdj/+hQTkmGsYcDM8qlEeiSlIpvxcTBRvE+VrH+Pp2bXbU7Yk6zcnmLvmERRvbnpEWLFoeizVAE4KkE6uhqR8XWJC+rIfuDokB919qY1FMKphNMQeN+Hl9lvkn4Ce0Q7z8cWG2VfzfWGbfP2oqgxqeOa63MI7AjaFCxU8tU0TZVJxubyBiOimZhCgBIkXPiSrj56G2FjH3gv3aPwMS8ZlVPYSR7tuotP4JoDrfMR2jTZhu9Uuw=
  file_glob: true
  file: FDAndroidClient/build/outputs/apk/*
  on:
    repo: MoriTanosuke/fd-android-client
    tags: true

